services:
  - type: worker
    name: Image-Editor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/sholoomail/Image-Editor.git
    branch: main
    envVars:
      - key: WEBHOOK 
        value: ANYTHING    
      - key: TG_BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: APP_HASH 
        sync: false
      - key: RemoveBG_API 
        sync: false
      - key: PYTHON_VERSION 
        value: 3.9.13
